// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import "./reset.css";
import localFont from "next/font/local";

const pretendard = localFont({
    src: "../static/fonts/PretendardVariable.woff2",
    display: "swap",
    weight: "45 920",
    variable: "--font-pretendard",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" className={`${pretendard.variable}`}>
        <body className={pretendard.className}>
        <div className="min-w-[320px] max-w-[600px] w-full mx-auto my-0">
            {children}
        </div>
        </body>
        </html>
    );
}
